/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'rgb(var(--color-primary) / <alpha-value>)',
          light: 'rgb(var(--color-primary-light) / <alpha-value>)',
        },
        secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
        accent: 'rgb(var(--color-accent) / <alpha-value>)',
        background: 'rgb(var(--color-background) / <alpha-value>)',
        foreground: 'rgb(var(--color-foreground) / <alpha-value>)',
        card: 'rgb(var(--color-card) / <alpha-value>)',
        muted: 'rgb(var(--color-muted) / <alpha-value>)',
        'muted-blue': 'rgb(var(--color-muted-blue) / <alpha-value>)',
      },
    },
  },
  safelist: [
    'font-semibold',
    'leading-tight',
    'text-4xl',
    'text-3xl',
    'text-2xl',
    'md:text-5xl',
    'md:text-4xl',
    'md:text-3xl',
    'lg:text-6xl',
    'py-16',
    'md:py-20',
    'px-4',
    'mx-auto',
    'max-w-7xl',
    'inline-flex',
    'items-center',
    'justify-center',
    'px-6',
    'py-3',
    'text-base',
    'font-medium',
    'rounded-lg',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-offset-2',
    'bg-transparent',
    'border',
    'relative',
    'mb-12',
    'pb-4',
    'after:absolute',
    'after:bottom-0',
    'after:left-0',
    'after:h-1',
    'after:w-24',
    'after:rounded-full',
    'fixed',
    'top-0',
    'left-0',
    'h-1',
    'z-50',
    'p-6',
    'rounded-xl',
    'shadow-md',
    'hover:shadow-lg',
  ],
  plugins: [],
}